# **Tugas 2**

### Melakukan Diskritasi


Carilah data yang bertipe numerik ( data klassifikasi)
1.   Lakukan proses diskritisasi dengan equal width dan equal frequency
2.   Lakukan proses diskritisasi  dengan basis entropy

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
cd drive/MyDrive/datamining

/content/drive/MyDrive/datamining

In [4]:
from matplotlib import rcParams, cycler
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import math
plt.ion()

In [5]:
dataset = pd.read_csv('https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv')
dataset

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [6]:
dataset.head()

   sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
def jarakData(i, j):
  P = 3
  M = 0
  for data in ['race/ethnicity', 'parental level of education', 'lunch' ]:
    if dataset[data][i] == dataset[data][j]:
      M = M + 1
  return (P-M)/P

In [ ]:
print(jarakData(0,1))
print(jarakData(0,2))
print(jarakData(0,3))

0.6666666666666666
0.3333333333333333
1.0

## Atribut Numerik

In [ ]:
def jarakData2(i, j, h):
  temp = 0
  for dataColomn in ['math score', 'reading score', 'writing score']:
    result = math.pow(abs((dataset[dataColomn][i]) - (dataset[dataColomn][j])), h)
  return result**(1/h)

In [ ]:
print(jarakData2(0,1,1))
print(jarakData2(0,2,1))
print(jarakData2(0,3,1))

14.0
19.0
30.0

In [ ]:
print(jarakData2(0,1,3))
print(jarakData2(0,2,3))
print(jarakData2(0,3,3))

13.999999999999998
18.999999999999996
29.999999999999993

There is a lot more that you can do with outputs (such as including interactive outputs)
with your book. For more information about this, see [the Jupyter Book documentation](https://jupyterbook.org)