# **Diskritisasi (Tugas 2)**

## Konsep Diskritisasi
Distraksi adalah sebuah transformasi kolom menjadi type data lain terutama categorial. Tujuannya untuk membuat data menjadi lebih optimal yang nantinya memudahkan untuk di analisis

Terdapat beberapa metode untuk diskritisasi yaitu :


1.   Metode Equal-Width Intervals
2.   Metode Equal-Frequency Intervals
3.   Metode Entropy

Assignment.
Tugas Melakukan diskritisasi
Carilah data yang bertipe numerik ( data klassifikasi)
1. Lakukan proses diskritisasi dengan equal width dan equal frequency
2. Lakukan proses diskritisasi dengan basis entropy

In [ ]:
import pandas as pd
import numpy as np
pd.options.mode.chained_assignment = None

## Mengambil dataset dari github

In [ ]:
dataset2 = pd.read_csv("https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv")
dataset2

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

## Equal-Width Intervals

Equal-width intervals adalah distraksi yang membagi data numerik menjadi beberapa kelompok dengan lebar kelompok yang kurang lebih sama besar.

Rumus membagi kedalam k interval
\begin{align}
        w = \frac {(max -min)}{b}
\end{align}

Rumus mencari batasan
\begin{align}
        min+w, min+2w, ... , min+(k-1)w
\end{align}

In [ ]:
data_sepal_length = dataset2[["sepal.length"]]
data_sepal_width = dataset2[["sepal.width"]]
data_petal_length = dataset2[["petal.length"]]
data_petal_width = dataset2[["petal.width"]]

In [ ]:
def cut(col, k):
    intervals = pd.cut(dataset2[col], k).value_counts().index.to_list()
    return [[interval.left, interval.right] for interval in intervals]

In [ ]:
def toCategory(list_interval, col):
    # get length interval
    length = len(list_interval)

    # Sorting interval
    sort_interval = np.sort(list_interval, axis=0)
    # Get Category from intervala
    categories = np.array([chr(65+i) for i in range(length)])[:, None]
    # combine into interval data
    intervals = np.hstack((sort_interval, categories))

    # Operate All data
    newCol = []
    for i, row in dataset2.iterrows():
        data = row[col]
        for interval in intervals:
            if data >= interval[0].astype(float) and data <= interval[1].astype(float):
                newCol.append(interval[2])
                break
    # return new coloumn category
    return np.array(newCol, dtype=str)

Mencari interval dengan dibagi menjadi 3 bagian

In [ ]:
interval_sepal_length = cut("sepal.length", 3)
interval_sepal_width = cut("sepal.width", 3)
interval_petal_length = cut("petal.length", 3)
interval_petal_width = cut("petal.width", 3)

print("interval sepal.length :", interval_sepal_length)
print("interval sepal.width  :", interval_sepal_width)
print("interval petal.length :", interval_petal_length)
print("interval petal.width  :", interval_petal_width)

interval sepal.length : [[5.5, 6.7], [4.296, 5.5], [6.7, 7.9]]
interval sepal.width  : [[2.8, 3.6], [1.998, 2.8], [3.6, 4.4]]
interval petal.length : [[2.967, 4.933], [0.994, 2.967], [4.933, 6.9]]
interval petal.width  : [[0.9, 1.7], [0.0976, 0.9], [1.7, 2.5]]

Menampilkan hasil dari pembagian category

In [ ]:
data_sepal_length["category"] = toCategory(interval_sepal_length, "sepal.length")
data_sepal_width["category"] = toCategory(interval_sepal_width, "sepal.width")
data_petal_length["category"] = toCategory(interval_petal_length, "petal.length")
data_petal_width["category"] = toCategory(interval_petal_width, "petal.width")

display(data_sepal_length)
display(data_sepal_width)
display(data_petal_length)
display(data_petal_width)

     sepal.length category
0             5.1        A
1             4.9        A
2             4.7        A
3             4.6        A
4             5.0        A
..            ...      ...
145           6.7        B
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

     sepal.width category
0            3.5        B
1            3.0        B
2            3.2        B
3            3.1        B
4            3.6        B
..           ...      ...
145          3.0        B
146          2.5        A
147          3.0        B
148          3.4        B
149          3.0        B

[150 rows x 2 columns]

     petal.length category
0             1.4        A
1             1.4        A
2             1.3        A
3             1.5        A
4             1.4        A
..            ...      ...
145           5.2        C
146           5.0        C
147           5.2        C
148           5.4        C
149           5.1        C

[150 rows x 2 columns]

     petal.width category
0            0.2        A
1            0.2        A
2            0.2        A
3            0.2        A
4            0.2        A
..           ...      ...
145          2.3        C
146          1.9        C
147          2.0        C
148          2.3        C
149          1.8        C

[150 rows x 2 columns]

## Equal-frequency Intervals
Equal-frequency intervals adalah distraksi yang membagi data numerik menjadi beberapa kelompok dengan jumlah anggota yang kurang lebih sama besar.

In [ ]:
data_sepal_length = dataset2[["sepal.length"]]
data_sepal_width = dataset2[["sepal.width"]]
data_petal_length = dataset2[["petal.length"]]
data_petal_width = dataset2[["petal.width"]]

In [ ]:
def qcut(col, k):
    intervals = pd.qcut(dataset2[col], k).value_counts().index.to_list()
    return [[interval.left, interval.right] for interval in intervals]

Membagi interval menjadi 3 bagian

In [ ]:
interval_sepal_length = qcut("sepal.length", 3)
interval_sepal_width = qcut("sepal.width", 3)
interval_petal_length = qcut("petal.length", 3)
interval_petal_width = qcut("petal.width", 3)

print("interval sepal.length :", interval_sepal_length)
print("interval sepal.width  :", interval_sepal_width)
print("interval petal.length :", interval_petal_length)
print("interval petal.width  :", interval_petal_width)

interval sepal.length : [[5.4, 6.3], [4.2989999999999995, 5.4], [6.3, 7.9]]
interval sepal.width  : [[1.999, 2.9], [2.9, 3.2], [3.2, 4.4]]
interval petal.length : [[2.633, 4.9], [0.999, 2.633], [4.9, 6.9]]
interval petal.width  : [[0.867, 1.6], [0.099, 0.867], [1.6, 2.5]]

In [ ]:
data_sepal_length["cateogry"] = toCategory(interval_sepal_length, "sepal.length")
data_sepal_width["cateogry"] = toCategory(interval_sepal_width, "sepal.width")
data_petal_length["cateogry"] = toCategory(interval_petal_length, "petal.length")
data_petal_width["cateogry"] = toCategory(interval_petal_width, "petal.width")

display(data_sepal_length)
display(data_sepal_width)
display(data_petal_length)
display(data_petal_width)

     sepal.length cateogry
0             5.1        A
1             4.9        A
2             4.7        A
3             4.6        A
4             5.0        A
..            ...      ...
145           6.7        C
146           6.3        B
147           6.5        C
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

     sepal.width cateogry
0            3.5        C
1            3.0        B
2            3.2        B
3            3.1        B
4            3.6        C
..           ...      ...
145          3.0        B
146          2.5        A
147          3.0        B
148          3.4        C
149          3.0        B

[150 rows x 2 columns]

     petal.length cateogry
0             1.4        A
1             1.4        A
2             1.3        A
3             1.5        A
4             1.4        A
..            ...      ...
145           5.2        C
146           5.0        C
147           5.2        C
148           5.4        C
149           5.1        C

[150 rows x 2 columns]

     petal.width cateogry
0            0.2        A
1            0.2        A
2            0.2        A
3            0.2        A
4            0.2        A
..           ...      ...
145          2.3        C
146          1.9        C
147          2.0        C
148          2.3        C
149          1.8        C

[150 rows x 2 columns]

## Entropy
Entropy merupakan informasi yang menggambarkan seberapa konsisten pemisah akan cocok dengan pengklasifikasi

Menganalisis sample data

In [ ]:
sample = dataset2[["sepal.length"]]
sample.describe()

       sepal.length
count    150.000000
mean       5.843333
std        0.828066
min        4.300000
25%        5.100000
50%        5.800000
75%        6.400000
max        7.900000

In [ ]:
np.random.seed(0)
sample["category"] = np.where(np.random.choice(2, sample.shape[0]) < 1, "A", "B" )
sample

     sepal.length category
0             5.1        A
1             4.9        B
2             4.7        B
3             4.6        A
4             5.0        B
..            ...      ...
145           6.7        A
146           6.3        B
147           6.5        B
148           6.2        B
149           5.9        B

[150 rows x 2 columns]

In [ ]:
def getOverollCategory(col):
    group = sample.loc[:, :].groupby("category").count()
    a = group.loc["A", col]
    b = group.loc["B", col]
    return (a, b, a+b)

In [ ]:
def splitter(value:float, col:str)->tuple:
    # get data less and greater from value
    less = sample[sample[col] <= value]
    greater = sample[sample[col] > value]

    # calculate into category for each data
    less_group = less.loc[:, :].groupby("category").count()
    greater_group = greater.loc[:, :].groupby("category").count()

    # get value based on category
    less_category_A = less_group.loc["A", col]

    less_category_B = less_group.loc["B", col]
    greater_category_A = greater_group.loc["A", col]
    greater_category_B = greater_group.loc["B", col]

    return (
        [less_category_A, less_category_B, less_category_A + less_category_B],
        [greater_category_A, greater_category_B, greater_category_A + greater_category_B]
    )

Rumus entrhopy
\begin{align}
    Entropy(D_1) = -\sum_{i=1}^m p_i \ log{_2} \ p_i
\end{align}

In [ ]:
def entropy(d):
    r1 = (d[0] / d[2]) * np.log2(d[0] / d[2])
    r2 = (d[1] / d[2]) * np.log2(d[1] / d[2])
    return np.sum([r1, r2]) * -1

Rumus info
\begin{align}
    info(D_{new}) = \frac {|D_1|}{|D|} Entrophy(D_2) +  \frac {|D_2|}{|D|} Entrophy(D_2)
\end{align}

In [ ]:
def info(d):
    r1 = (d[0][2] / sample.shape[0])  * entropy(d[0])
    r2 = (d[1][2] / sample.shape[0]) * entropy(d[1])
    return r1 + r2

Rumus Gain
\begin{align}
    gain = D_{new} - D_{initial}
\end{align}

In [ ]:
def gain(Einitial, Enew):
    return Einitial - Enew

Membuat Dinitial

In [ ]:
D = getOverollCategory("sepal.length")
entropy_d = entropy(D)
print(D)
display(entropy_d)

(68, 82, 150)

0.993707106604508

Hasil Split 1

In [ ]:
split1 = splitter(4.4, "sepal.length")
info_split1 = info(split1)
gain(entropy_d, info_split1)

0.003488151753460178

Hasil Split 2

In [ ]:
split2 = splitter(5.5, "sepal.length")
info_split2 = info(split2)
gain(entropy_d, info_split2)

0.012302155146638905

Hasil split 3

In [ ]:
split3 = splitter(7.0, "sepal.length")
info_split3 = info(split3)
gain(entropy_d, info_split3)

0.0005490214732508658